server:
  port: 8081

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL}
    driverClassName: org.h2.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    test-on-borrow: true
    validation-query: SELECT 1;
    validation-interval: 3000
    test-while-idle: true
    time-between-eviction-runs-millis: 30000
    remove-abandoned: true
    remove-abandoned-timeout: 30
    hikari:
      connectionTimeout: 40000
      idleTimeout: 50000
      maxLifeTime: 30000

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

application:
  name: dev-profile