spring:
  config:
    activate:
      on-profile: dev

  # datasource: é onde configura as conexões com a base de dados;
  datasource:
    url: jdbc:h2:mem:test # connection string
    driverClassName: org.h2.Driver # driver do banco utilizado para conexão
    username: admin
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

application.name: dev-profile